#!/bin/bash

diff -y --suppress-common-lines <(git show -U0 --oneline $1 | sed 's/^--- \(.*\)$/diff1 \1/g')  <(git show -U0 --oneline $2 | sed 's/^--- \(.*\)$/diff2 \1/g') | sed -n '/\(index\).*/!p'  | colordiff